/*
 * Gosp API Specification
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type AuthResponse struct {

	AccessToken string `json:"accessToken,omitempty"`

	AccessExpiresIn int32 `json:"accessExpiresIn,omitempty"`

	RefreshToken string `json:"refreshToken,omitempty"`

	RefreshExpiresIn int32 `json:"refreshExpiresIn,omitempty"`

	Type string `json:"type,omitempty"`
}
