/*
 * Gosp API Specification
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type Message struct {

	Id string `json:"id,omitempty"`

	SenderId string `json:"senderId,omitempty"`

	ChatId string `json:"chatId,omitempty"`

	Content string `json:"content,omitempty"`

	Timestamp string `json:"timestamp,omitempty"`

	Status string `json:"status,omitempty"`

	Attachments []Attachment `json:"attachments,omitempty"`
}
