/*
 * Gosp API Specification
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type Attachment struct {

	Id string `json:"id,omitempty"`

	Type string `json:"type,omitempty"`

	Url string `json:"url,omitempty"`

	Size int32 `json:"size,omitempty"`

	MimeType string `json:"mimeType,omitempty"`

	Inline bool `json:"inline,omitempty"`
}
