/*
 * Gosp API Specification
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type User struct {

	Id string `json:"id,omitempty"`

	Username string `json:"username,omitempty"`

	DisplayName string `json:"displayName,omitempty"`

	AvatarUrl string `json:"avatarUrl,omitempty"`

	Status string `json:"status,omitempty"`

	LastSeen string `json:"lastSeen,omitempty"`
}
