/*
 * Gosp API Specification
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"net/http"

	"github.com/gin-gonic/gin"
)

// Route is the information for every URI.
type Route struct {
	// Name is the name of this Route.
	Name		string
	// Method is the string for the HTTP method. ex) GET, POST etc..
	Method		string
	// Pattern is the pattern of the URI.
	Pattern	 	string
	// HandlerFunc is the handler function of this route.
	HandlerFunc	gin.HandlerFunc
}

// NewRouter returns a new router.
func NewRouter(handleFunctions ApiHandleFunctions) *gin.Engine {
	return NewRouterWithGinEngine(gin.Default(), handleFunctions)
}

// NewRouter add routes to existing gin engine.
func NewRouterWithGinEngine(router *gin.Engine, handleFunctions ApiHandleFunctions) *gin.Engine {
	for _, route := range getRoutes(handleFunctions) {
		if route.HandlerFunc == nil {
			route.HandlerFunc = DefaultHandleFunc
		}
		switch route.Method {
		case http.MethodGet:
			router.GET(route.Pattern, route.HandlerFunc)
		case http.MethodPost:
			router.POST(route.Pattern, route.HandlerFunc)
		case http.MethodPut:
			router.PUT(route.Pattern, route.HandlerFunc)
		case http.MethodPatch:
			router.PATCH(route.Pattern, route.HandlerFunc)
		case http.MethodDelete:
			router.DELETE(route.Pattern, route.HandlerFunc)
		}
	}

	return router
}

// Default handler for not yet implemented routes
func DefaultHandleFunc(c *gin.Context) {
	c.String(http.StatusNotImplemented, "501 not implemented")
}

type ApiHandleFunctions struct {

	// Routes for the DefaultAPI part of the API
	DefaultAPI DefaultAPI
}

func getRoutes(handleFunctions ApiHandleFunctions) []Route {
	return []Route{ 
		{
			"CreateChat",
			http.MethodPost,
			"/chats",
			handleFunctions.DefaultAPI.CreateChat,
		},
		{
			"CreateMessage",
			http.MethodPost,
			"/chats/:chatId/messages",
			handleFunctions.DefaultAPI.CreateMessage,
		},
		{
			"DeleteChat",
			http.MethodDelete,
			"/chats/:chatId",
			handleFunctions.DefaultAPI.DeleteChat,
		},
		{
			"GetChat",
			http.MethodGet,
			"/chats/:chatId",
			handleFunctions.DefaultAPI.GetChat,
		},
		{
			"GetChats",
			http.MethodGet,
			"/chats",
			handleFunctions.DefaultAPI.GetChats,
		},
		{
			"GetMe",
			http.MethodGet,
			"/users/me",
			handleFunctions.DefaultAPI.GetMe,
		},
		{
			"GetMessage",
			http.MethodGet,
			"/chats/:chatId/messages/:messageId",
			handleFunctions.DefaultAPI.GetMessage,
		},
		{
			"GetMessages",
			http.MethodGet,
			"/chats/:chatId/messages",
			handleFunctions.DefaultAPI.GetMessages,
		},
		{
			"GetUsersList",
			http.MethodGet,
			"/users",
			handleFunctions.DefaultAPI.GetUsersList,
		},
		{
			"LoginUser",
			http.MethodPost,
			"/auth/login",
			handleFunctions.DefaultAPI.LoginUser,
		},
		{
			"RegisterUser",
			http.MethodPost,
			"/auth/register",
			handleFunctions.DefaultAPI.RegisterUser,
		},
		{
			"UpdateChat",
			http.MethodPut,
			"/chats/:chatId",
			handleFunctions.DefaultAPI.UpdateChat,
		},
		{
			"UpdateMessage",
			http.MethodPut,
			"/chats/:chatId/messages/:messageId",
			handleFunctions.DefaultAPI.UpdateMessage,
		},
	}
}
